/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CredentialRegistry } from "./CredentialRegistry";
export * as factories from "./factories";
export { CredentialRegistry__factory } from "./factories/CredentialRegistry__factory";
